name:                blog-src
version:             0.1.0.0
github:              "wei2912/blog-src"
license:             MIT
author:              "Ng Wei En"
maintainer:          "weien1292@gmail.com"
copyright:           "2018 Ng Wei En"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/wei2912/blog-src#readme>.

dependencies:
- base
- containers
- hakyll
- hakyll-images
- hakyll-sass
- pandoc

executables:
  blog-src:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

